name: On PR or push to main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (npm install)
        working-directory: ./
        run: |
          npm install

      #         - name: Lint
      #           working-directory: ./
      #           run: npm run lint

      - name: npm run build:ci
        working-directory: ./
        run: |
          npm run build:ci core

      - name: test
        working-directory: ./
        run: |
          npm run test-headless
